### PR TITLE
Fix build by using ubuntu-20.04

### PR DESCRIPTION
**Pull request by max-mapper**
seeing if this works

### CODE REVIEW

**Comment by max-mapper** [comment]
It seems the build works on ubuntu-20.04 but not the new ubuntu-22.04. I was using `ubuntu-latest` before and so removing that fixes it

**Comment by max-mapper** [comment]
FYI I think the root issue is gcc 9.x works to build tronko, but using newer gcc errors with: `/usr/bin/ld: /tmp/cclzNx5k.o:(.bss+0x0): multiple definition of `hashmap_base'; /tmp/ccvj49UW.o:(.bss+0x0): first defined here` which seems to be an issue with how the hashmap library defines structs in its `.h` files
